Algoritmo "Atidade 5 senha"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2026
Var
// Seção de Declarações das variáveis 
  s, l: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   s <- "marcos123"
   Escreval(" Informe sua Senha; ")
   leia(l)
   se s = l entao
    escreval(" Acesso permitido")
    senao
    escreval(" senha incorreta, Tente novamente")
    fimse
   

Fimalgoritmo