Algoritmo "Atividade 4 calculo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2026
Var
// Seção de Declarações das variáveis 
    a, b, n: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Escreval("Informe um numero: ")
     leia (a)
     enquanto n <= 10 faca
     b <- a * n
     escreval (a, "x", n, "=", b)
     n<- n +1
  Fimenquanto
Fimalgoritmo