Algoritmo "Atividade 1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2026
Var
// Seção de Declarações das variáveis 
c: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    c <- 0
    enquanto c <= 10 faca
    escreval (c)
    c <- c + 1
    fimenquanto

Fimalgoritmo