Algoritmo "Atividade 7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2026
Var
// Seção de Declarações das variáveis 
n, s, i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  s <- 0
  i <- 1
  Escreval(" informe um numero: ")
  leia(n)
  Enquanto i <= n faca
   i <- i + s
   s <- s + 1
   fimenquanto
   escreval(" a soma dos numeros Deu : ", s)

Fimalgoritmo